#pragma once
/*
* This file is part of libsidplayfp, a SID player engine.
*
* Copyright 2023 Michael Hartmann
* Copyright 2011-2013 Leandro Nini <drfiemost@users.sourceforge.net>
* Copyright 2007-2010 Antti Lankila
* Copyright 2004 Dag Lem <resid@nimrod.no>
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

#include <cmath>
#include <cstdint>
#include <vector>

#include "../../../EZ/config.h"

#if SID_X86
	#include <immintrin.h>
	// the TU is compiled for the SSE4.2 baseline, so the AVX2 kernel needs its own target
	#if defined(__clang__) || defined(__GNUC__)
		#define SIDR_TARGET_AVX2 __attribute__(( target( "avx2" ) ))
	#else
		#define SIDR_TARGET_AVX2
	#endif
#elif SID_NEON
	#include <arm_neon.h>
#endif

namespace reSIDfp
{

/**
* This is the theoretically correct (and computationally intensive) audio sample generation.
* The samples are generated by resampling to the specified sampling frequency.
* The work rate is inversely proportional to the percentage of the bandwidth
* allocated to the filter transition band.
*
* This implementation is based on the paper "A Flexible Sampling-Rate Conversion Method",
* by J. O. Smith and P. Gosset, or rather on the expanded tutorial on the
* [Digital Audio Resampling Home Page](http://www-ccrma.stanford.edu/~jos/resample/).
*
* By building shifted FIR tables with samples according to the sampling frequency,
* this implementation dramatically reduces the computational effort in the
* filter convolutions, without any loss of accuracy.
* The filter convolutions are also vectorizable on current hardware.
*/
class SincResampler final
{
private:
	// Size of the ring buffer, must be a power of 2
	static const int RINGSIZE = 2048;

	// Table of the fir filter coefficients
	std::vector<int16_t>	firTable;

	int sampleIndex = 0;

	/// Filter resolution
	int firRES;

	/// Filter length
	int firN;

	int cyclesPerSample = 0;

	int sampleOffset = 0;

	int outputValue = 0;

	int32_t	sample[ RINGSIZE * 2 ];

	/**
	* Convolution kernels: int32 samples * int16 sinc coefficients, int32 sum.
	* All variants are bit-exact against the scalar loop (wrap-around integer
	* addition is associative, and the low 32 bits of the products are identical),
	* so the choice of kernel never changes the audio.
	*/
	//-----------------------------------------------------------------------------
	static int convolveScalar ( const int32_t* __restrict__ a, const int16_t* __restrict__ b, const int n ) noexcept
	{
		auto	out = 0;

		[[ assume ( n > 0 ) ]];
		for ( auto i = 0; i < n; ++i )
			out += a[ i ] * b[ i ];

		return out;
	}

#if SID_X86
	static int convolveSSE4 ( const int32_t* __restrict__ a, const int16_t* __restrict__ b, const int n ) noexcept
	{
		auto	acc0 = _mm_setzero_si128 ();
		auto	acc1 = _mm_setzero_si128 ();

		auto	i = 0;
		for ( ; i + 8 <= n; i += 8 )
		{
			const auto	b16 = _mm_loadu_si128 ( (const __m128i*)( b + i ) );
			const auto	lo = _mm_cvtepi16_epi32 ( b16 );
			const auto	hi = _mm_cvtepi16_epi32 ( _mm_srli_si128 ( b16, 8 ) );

			acc0 = _mm_add_epi32 ( acc0, _mm_mullo_epi32 ( _mm_loadu_si128 ( (const __m128i*)( a + i ) ), lo ) );
			acc1 = _mm_add_epi32 ( acc1, _mm_mullo_epi32 ( _mm_loadu_si128 ( (const __m128i*)( a + i + 4 ) ), hi ) );
		}

		acc0 = _mm_add_epi32 ( acc0, acc1 );
		acc0 = _mm_add_epi32 ( acc0, _mm_shuffle_epi32 ( acc0, _MM_SHUFFLE ( 1, 0, 3, 2 ) ) );
		acc0 = _mm_add_epi32 ( acc0, _mm_shuffle_epi32 ( acc0, _MM_SHUFFLE ( 2, 3, 0, 1 ) ) );
		auto	out = _mm_cvtsi128_si32 ( acc0 );

		for ( ; i < n; ++i )
			out += a[ i ] * b[ i ];

		return out;
	}

	SIDR_TARGET_AVX2 static int convolveAVX2 ( const int32_t* __restrict__ a, const int16_t* __restrict__ b, const int n ) noexcept
	{
		auto	acc0 = _mm256_setzero_si256 ();
		auto	acc1 = _mm256_setzero_si256 ();

		auto	i = 0;
		for ( ; i + 16 <= n; i += 16 )
		{
			const auto	lo = _mm256_cvtepi16_epi32 ( _mm_loadu_si128 ( (const __m128i*)( b + i ) ) );
			const auto	hi = _mm256_cvtepi16_epi32 ( _mm_loadu_si128 ( (const __m128i*)( b + i + 8 ) ) );

			acc0 = _mm256_add_epi32 ( acc0, _mm256_mullo_epi32 ( _mm256_loadu_si256 ( (const __m256i*)( a + i ) ), lo ) );
			acc1 = _mm256_add_epi32 ( acc1, _mm256_mullo_epi32 ( _mm256_loadu_si256 ( (const __m256i*)( a + i + 8 ) ), hi ) );
		}

		auto	acc = _mm_add_epi32 ( _mm256_castsi256_si128 ( _mm256_add_epi32 ( acc0, acc1 ) ),
									  _mm256_extracti128_si256 ( _mm256_add_epi32 ( acc0, acc1 ), 1 ) );
		acc = _mm_add_epi32 ( acc, _mm_shuffle_epi32 ( acc, _MM_SHUFFLE ( 1, 0, 3, 2 ) ) );
		acc = _mm_add_epi32 ( acc, _mm_shuffle_epi32 ( acc, _MM_SHUFFLE ( 2, 3, 0, 1 ) ) );
		auto	out = _mm_cvtsi128_si32 ( acc );

		for ( ; i < n; ++i )
			out += a[ i ] * b[ i ];

		return out;
	}
#elif SID_NEON
	static int convolveNEON ( const int32_t* __restrict__ a, const int16_t* __restrict__ b, const int n ) noexcept
	{
		auto	acc0 = vdupq_n_s32 ( 0 );
		auto	acc1 = vdupq_n_s32 ( 0 );

		auto	i = 0;
		for ( ; i + 8 <= n; i += 8 )
		{
			const auto	b16 = vld1q_s16 ( b + i );

			acc0 = vmlaq_s32 ( acc0, vld1q_s32 ( a + i ), vmovl_s16 ( vget_low_s16 ( b16 ) ) );
			acc1 = vmlaq_s32 ( acc1, vld1q_s32 ( a + i + 4 ), vmovl_s16 ( vget_high_s16 ( b16 ) ) );
		}

		auto	out = vaddvq_s32 ( vaddq_s32 ( acc0, acc1 ) );

		for ( ; i < n; ++i )
			out += a[ i ] * b[ i ];

		return out;
	}
#endif

	using ConvolveFn = int (*) ( const int32_t*, const int16_t*, int );

	static ConvolveFn selectConvolve () noexcept
	{
	#if SID_X86
		return ( libsidplayEZ::simdLevel () >= libsidplayEZ::SIMD_AVX2 ) ? &convolveAVX2 : &convolveSSE4;
	#elif SID_NEON
		return &convolveNEON;
	#else
		return &convolveScalar;
	#endif
	}

	static inline const ConvolveFn convolve = selectConvolve ();

	//-----------------------------------------------------------------------------
	sidinline int fir ( int subcycle ) noexcept
	{
		// Find the first of the nearest fir tables close to the phase
		auto		firTableFirst = subcycle * firRES >> 10;
		const auto	firTableOffset = ( subcycle * firRES ) & 0x3FF;

		// Find firN most recent samples, plus one extra in case the FIR wraps
		auto	sampleStart = sampleIndex - firN + RINGSIZE - 1;

		const auto	v1 = ( convolve ( sample + sampleStart, firTable.data () + firTableFirst * firN, firN ) + ( 1 << 14 ) ) >> 15;

		// Use next FIR table, wrap around to first FIR table using previous sample
		if ( ++firTableFirst == firRES ) [[ unlikely ]]
		{
			firTableFirst = 0;
			++sampleStart;
		}

		const auto	v2 = ( convolve ( sample + sampleStart, firTable.data () + firTableFirst * firN, firN ) + ( 1 << 14 ) ) >> 15;

		// Linear interpolation between the sinc tables yields good approximation for the exact value
		return v1 + ( firTableOffset * ( v2 - v1 ) >> 10 );
	}

public:
	/**
	* Use a clock freqency of 985248Hz for PAL C64, 1022730Hz for NTSC C64.
	* For resampling, the ratio between the clock frequency
	* and the sample frequency is limited as follows:
	*   125*clock_freq/sample_freq < 16384
	*
	* E.g. provided a clock frequency of ~ 1MHz, the sample frequency
	* can not be set lower than ~ 8kHz.
	* A lower sample frequency would make the resampling code overfill
	* its 16k sample ring buffer.
	*
	* @param clockFrequency System clock frequency at Hz
	* @param samplingFrequency Desired output sampling rate
	* @param highestAccurateFrequency passband frequency limit
	*/
	void setup ( double clockFrequency, double samplingFrequency, double highestAccurateFrequency ) noexcept;

	[[ nodiscard ]] sidinline bool input ( const int input ) noexcept
	{
		auto	ready = false;

		sample[ sampleIndex ] = sample[ sampleIndex + RINGSIZE ] = input;
		sampleIndex = ( sampleIndex + 1 ) & ( RINGSIZE - 1 );

		if ( sampleOffset < 1024 ) [[ likely ]]
		{
			outputValue = fir ( sampleOffset );
			ready = true;
			sampleOffset += cyclesPerSample;
		}

		sampleOffset -= 1024;

		return ready;
	}

	[[ nodiscard ]] sidinline int output () const noexcept { return outputValue; }

	void reset () noexcept;
};

} // namespace reSIDfp
