#pragma once
/*
* This file is part of libsidplayfp, a SID player engine.
*
* Copyright 2023 Michael Hartmann
* Copyright 2011-2013 Leandro Nini <drfiemost@users.sourceforge.net>
* Copyright 2007-2010 Antti Lankila
* Copyright 2004 Dag Lem <resid@nimrod.no>
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

#include <cmath>
#include <vector>

#include "../../../EZ/config.h"

namespace reSIDfp
{

/**
* This is the theoretically correct (and computationally intensive) audio sample generation.
* The samples are generated by resampling to the specified sampling frequency.
* The work rate is inversely proportional to the percentage of the bandwidth
* allocated to the filter transition band.
*
* This implementation is based on the paper "A Flexible Sampling-Rate Conversion Method",
* by J. O. Smith and P. Gosset, or rather on the expanded tutorial on the
* [Digital Audio Resampling Home Page](http://www-ccrma.stanford.edu/~jos/resample/).
*
* By building shifted FIR tables with samples according to the sampling frequency,
* this implementation dramatically reduces the computational effort in the
* filter convolutions, without any loss of accuracy.
* The filter convolutions are also vectorizable on current hardware.
*/
class SincResampler final
{
private:
	// Size of the ring buffer, must be a power of 2
	static const int RINGSIZE = 2048;

	// Table of the fir filter coefficients
	std::vector<int16_t>	firTable;

	int sampleIndex = 0;

	/// Filter resolution
	int firRES;

	/// Filter length
	int firN;

	int cyclesPerSample = 0;

	int sampleOffset = 0;

	int outputValue = 0;

	int32_t	sample[ RINGSIZE * 2 ];

	/**
	* Calculate convolution with sample and sinc
	*
	* @param a sample buffer input
	* @param b sinc buffer
	* @param bLength length of the sinc buffer
	* @return convolved result
	*/
	//-----------------------------------------------------------------------------
	sidinline int fir ( int subcycle )
	{
		auto convolve = [] ( const int32_t* const __restrict__ a, const int16_t* const __restrict__ b, const int bLength )
		{
			auto    out = 0;

			[[ assume ( bLength > 0 ) ]];
			for ( auto i = 0; i < bLength; ++i )
				out += a[ i ] * b[ i ];

			return ( out + ( 1 << 14 ) ) >> 15;
		};

		// Find the first of the nearest fir tables close to the phase
		auto		firTableFirst = subcycle * firRES >> 10;
		const auto	firTableOffset = ( subcycle * firRES ) & 0x3FF;

		// Find firN most recent samples, plus one extra in case the FIR wraps
		auto	sampleStart = sampleIndex - firN + RINGSIZE - 1;

		const auto	v1 = convolve ( sample + sampleStart, firTable.data () + firTableFirst * firN, firN );

		// Use next FIR table, wrap around to first FIR table using previous sample
		if ( ++firTableFirst == firRES ) [[ unlikely ]]
		{
			firTableFirst = 0;
			++sampleStart;
		}

		const auto	v2 = convolve ( sample + sampleStart, firTable.data () + firTableFirst * firN, firN );

		// Linear interpolation between the sinc tables yields good approximation for the exact value
		return v1 + ( firTableOffset * ( v2 - v1 ) >> 10 );
	}

public:
	/**
	* Use a clock freqency of 985248Hz for PAL C64, 1022730Hz for NTSC C64.
	* For resampling, the ratio between the clock frequency
	* and the sample frequency is limited as follows:
	*   125*clock_freq/sample_freq < 16384
	*
	* E.g. provided a clock frequency of ~ 1MHz, the sample frequency
	* can not be set lower than ~ 8kHz.
	* A lower sample frequency would make the resampling code overfill
	* its 16k sample ring buffer.
	*
	* @param clockFrequency System clock frequency at Hz
	* @param samplingFrequency Desired output sampling rate
	* @param highestAccurateFrequency passband frequency limit
	*/
	void setup ( double clockFrequency, double samplingFrequency, double highestAccurateFrequency );

	[[ nodiscard ]] sidinline bool input ( const int input )
	{
		auto	ready = false;

		sample[ sampleIndex ] = sample[ sampleIndex + RINGSIZE ] = input;
		sampleIndex = ( sampleIndex + 1 ) & ( RINGSIZE - 1 );

		if ( sampleOffset < 1024 ) [[ likely ]]
		{
			outputValue = fir ( sampleOffset );
			ready = true;
			sampleOffset += cyclesPerSample;
		}

		sampleOffset -= 1024;

		return ready;
	}

	[[ nodiscard ]] sidinline int output () const { return outputValue; }

	void reset ();
};

} // namespace reSIDfp
